### ISSUE TITLE
code issues

### ISSUE THREAD

**Issue by gr915** [lsqshr/Rivulet-Neuron-Tracing-Toolbox#17] opened 2017-08-01 12:42 UTC
hello!
problem one ：your main program is tracegold.m ?
problem two :I run the main program， It will show an error：
                                   Error in trace (line 104)
                                    axes(ax);
                                  Error in tracegold (line 1)
         tree = trace('C:\Users\gongrong\Desktop\OP_1_stack.v3draw', 'classify', 0.5, true,1, 0.95, true, false);
Is not the value 0.95 setting error?

**Comment by lsqshr** [comment] 2017-08-01 13:54
@gr915 
Thanks for your interests! The main entrance for the algorithm is trace.m. However, it was designed for the GUI app & you need to silent the plotting when you only run it in the console. 

@donghaozhang Can you help giving out an example console line to run the Rivulet tracing itself with `trace.m`? I do not have a Matlab license on my workstation here to test right now.

Also pls note, the most recent Rivulet algorithm is implemented in https://github.com/RivuletStudio/rivuletpy and Vaa3D up-to-date sources which should generate much better results.

**Comment by donghaozhang** [comment] 2017-08-02 01:52
@gr915 We will suggest to rivuletpy first. If you want to try matlab version, you can guide gui(matlab command line). Then press green button, then load the image(.tif or v3draw).  Then choose a threshold and press trace. trace.m is the main function. I will see I can find an example console line.

**Comment by gr915** [comment] 2017-08-02 02:07
thank you for your answers, but I want to transfer trace.m by myself ,do not  use your package app. i want to run your code step by step, it will help me understanding code.
for examply: your “test”folder have tracegold.m transfer trace.m,but run  tracegold.m,it will show error.

**Comment by donghaozhang** [comment] 2017-08-02 02:08
@gr915 I have a file similar to command-line of trace.m
clear all; close all;
fprintf('Prepare for the original image : I binary image : bI\n');
% The following line is designed for zebrafish
% load('midzebraI.mat');
% mouseRGC
% load('miccaidata\experimentmouseRGC\mouseRGCresampled.mat');
% load('miccaidata\experimentjaneliafly\janeliaflypart2ex5resampled.mat');
% mid
% The first input variable I is inside op1resample.mat 
% load('op1resample.mat');
% outfilename = 'op1resample.swc';
load('zebraI.mat');
% load first5
% load('miccaidata\experimentfirst5\first5.mat')
% outfilename = 'janelia.swc';
% outfilename = 'op1resample.swc';
prefix_outfilename = 'miccaidata\experimentfirst5\first5';
% prefix_outfilename = 'miccaidata\experimentmouseRGC\mouseRGC';
% prefix_outfilename = 'miccaidata\experimentjaneliafly\janelia';
suffix_outfilename = '.swc';
% foreground_speed_list = [50 5 500 0.5];
foreground_speed_list = [30 40 50 60];
afmp_list = [0.93];
% midzebra threshold
% threshold = 70; 
% mouseRGC threshold
% threshold = 8;
% janeliafly part2 ex5
threshold = 40;
I_original = I;
I = I > threshold;
% oofilter;
% the following line load the binary image of mouse RGC
% load('miccaidata\experimentmouseRGC\mouseRGCresampledbI.mat');
% the following line load the binary image of janelia fly
% load('miccaidata\experimentjaneliafly\janeliaflybI.mat');
% save('mat\bI.mat','I');
% 
% i = 1;
% for i = 1 : numel(foreground_speed_list)  
for i = 1 : numel(afmp_list)  

    % The second input variable is plot
    plot_value = false;
    plot = false;

    % The third input variable is percentage 
    percentage = 0.98;

    % The fourth input vairable is rewire
    rewire =  false;

    % The fifth input vairable is gap 
    gap = 10;

    % The sixth input variable is ax
    ax_value = false;

    % The seventh input variable is dumpcheck
    dumpcheck = true;

    % The eighth input variable is connectrate
    connectrate = 1.2;

    % The ninth input variable is branchlen
    branchlen = 10;

    % The tenth input variable is somagrowthcheck
    somagrowthcheck = false;

    % The eleventh input vairable is soma structure
    % We only test the anisotropic fast marching at this point 
    % so we do not include soma in this script 

    % The twelfth input variable is cleanercheck
    cleanercheck = false;

    % The thirteenth input variable is dtimageflag
    dtimageflag = false;
    

    % The fourteenth input variable is tmapflag
    atmapflag = true;

    % The fifteenth input variable is ignoreradiusflag
    ignoreradiusflag = true;

    % The sixteenth input variable is prunetreeflag
    prunetreeflag = false;

    % The seventeen input variable is anisotropic fast marching 
    % afmp = 0.95;
    afmp = afmp_list(i);

    % The eighteenth input variable is to use speedimage to calculate diffusion matrix or not
    speedastensorflag = false;

    % The nineteenth input variable is to use hessianmatrix from oof at multiscale to calculate diffusion matrix or not
    oofhmflag = true;

    % The twentieth input variable control whether we will highlight the direction of first eigenvector 
    boostveconeflag = true; 

    % The twenty-first input variable control whether we will highlight the direction of first eigenvector 
    skeletonspeedflag = false;


    if plot
        axes(ax);
    end
    if (~dtimageflag)
        disp('Distance transform');
        notbI = not(I>0.5);
        bdist = bwdist(notbI, 'Quasi-Euclidean');
        bdist = bdist .* double(I);
        bdist = double(bdist);
    end

    disp('Looking for the source point...')
    if somagrowthcheck
        SourcePoint = [soma.x; soma.y; soma.z];
        somaidx = find(soma.I == 1);
        [somax, somay, somaz] = ind2sub(size(soma.I), somaidx);
        % Find the soma radius
        d = pdist2([somax, somay, somaz], [soma.x, soma.y, soma.z]);
        maxD = max(d);
    else
        [SourcePoint, maxD] = maxDistancePoint(bdist, I, true);
        fprintf('SourcePoint x: %d, SourcePoint y: %d, SourcePoint z: %d\n', SourcePoint(1), SourcePoint(2), SourcePoint(3));
    end
    disp('Make the speed image...')
    SpeedImage=(bdist/maxD).^4;
    % clear bdist;
    
    SpeedImage(SpeedImage==0) = 1e-10;
	if plot
        axes(ax);
	end	
	disp('marching...');
    % Testing the relations of foreground speed coefficient 
    % foreground_speed_coeff = foreground_speed_list(i);
    foreground_speed_coeff = 60;    
    if (~atmapflag)
        T = msfm(SpeedImage, SourcePoint, false, false);
        fprintf('Multistencils fast marching is running.\n');
    else
        T = afm(I_original, threshold, foreground_speed_coeff, speedastensorflag, oofhmflag, afmp, boostveconeflag, skeletonspeedflag);
        fprintf('Anisotropic fast marching is running.\n');
    end
%     subplot(2,2,i)
    T_tmp = squeeze(max(T,[],3));
%     imagesc(permute(T_tmp, [2 1])); 
%     title(['Time map ' num2str(i)]);
    % save('T_rivulet.mat','T');
    szT = size(T);
    fprintf('the size of time map, x is : %d, y is : %d, z is : %d\n', szT(1), szT(2), szT(3));
    disp('Finish marching')

    if somagrowthcheck
        fprintf('Mark soma label on time-crossing map\n')
        T(soma.I==1) = -2;
    end

    if plot
    	hold on 
    end

    tree = []; % swc tree
    if somagrowthcheck
        fprintf('Initialization of swc tree.\n'); 
        tree(1, 1) = 1;
        tree(1, 2) = 2;
        tree(1, 3) = soma.x;
        tree(1, 4) = soma.y;
        tree(1, 5) = soma.z;
        % fprintf('source point x : %d, y : %d, z : %d.\n', uint8(SourcePoint(1)), uint8(SourcePoint(2)), uint8(SourcePoint(3)));         
        tree(1, 6) = 1;
        tree(1, 7) = -1;
    end

    prune = true;
	% Calculate gradient of DistanceMap
	disp('Calculating gradient...')
    grad = distgradient(T);
    if plot
        axes(ax);
    end
    S = {};
    B = zeros(size(T));
    if somagrowthcheck
        B = B | (soma.I>0.5);
    end
    lconfidence = [];
    if plot
	    [x,y,z] = sphere;
	    plot3(x + SourcePoint(2), y + SourcePoint(1), z + SourcePoint(3), 'ro');
	end

    unconnectedBranches = {};
    printcount = 0;
    printn = 0;
    counter = 1;
    dumplist = [];
    branchlist = [];
    mergedlist = [];
    swclist = [];
    branchcounter = 0;
    hold on
    while(true)
        branchcounter = 1 + branchcounter;  
	    StartPoint = maxDistancePoint(T, I, true);

	    if plot
		    plot3(x + StartPoint(2), y + StartPoint(1), z + StartPoint(3), 'ro');
		end

	    if T(StartPoint(1), StartPoint(2), StartPoint(3)) == 0 || I(StartPoint(1), StartPoint(2), StartPoint(3)) == 0
	    	break;
	    end

	    [l, dump, merged, somamerged] = shortestpath2(T, grad, I, tree, StartPoint, SourcePoint, 1, 'rk4', gap);
        % scatter3(l(:,2), l(:,1), l(:,3));
        dump = false;
        merged = true;
        dumplist = [dump; dumplist];
        branchlist = [l; branchlist];
        if size(l, 1) == 0
            l = StartPoint'; % Make sure the start point will be erased
        end
        % scatter3(l(:,2), l(:,1), l(:,3), 'r');
	    % Get radius of each point from distance transform
	    radius = zeros(size(l, 1), 1);
	    parfor r = 1 : size(l, 1)
            radius(r) = getradius(I, l(r, 1), l(r, 2), l(r, 3));
            % radius(r) = getradiusoof(I, l(r, 1), l(r, 2), l(r, 3), eigvoof)
		    % radius(r) = getradiusfrangi(I, whatScale, l(r, 1), l(r, 2), l(r, 3));
		end
	    radius(radius < 1) = 1;
		% assert(size(l, 1) == size(radius, 1));

        [covermask, centremask] = binarysphere3d(size(T), l, radius);
	    % Remove the traced path from the timemap
        if cleanercheck & size(l, 1) > branchlen
            covermask = augmask(covermask, I, l, radius);
        end

        % covermask(StartPoint(1), StartPoint(2), StartPoint(3)) = 3; % Why? Double check if it is nessensary - SQ

        T(covermask) = -1;
        T(centremask) = -3;

	    % if cleanercheck
     %        T(wash==1) = -1;
     %    end

	    % Add l to the tree
	    if ~((dump) && dumpcheck)
            % scatter3(l(:,2), l(:,1), l(:,3), 'b');
            swclist = [swclist;branchcounter];
		    [tree, newtree, conf, unconnected] = addbranch2tree(tree, l, merged, connectrate, radius, I, branchlen, plot, somamerged);
            lconfidence = [lconfidence, conf];
		end

        B = B | covermask;

        percent = sum(B(:) & I(:)) / sum(I(:));
        if plot
            axes(ax);
        end
        printn = printn + 1;
        if printn > 1
            fprintf(1, repmat('\b',1,printcount));
            printcount = fprintf('Tracing percent: %f%%\n', percent*100);
        end
        if percent >= percentage
        	disp('Coverage reached end tracing...')
        	break;
        end
        counter = counter + 1;

    end

    meanconf = mean(lconfidence);

    if cleanercheck
        disp('Fixing topology')
        tree = fixtopology(tree);
    end
    if prunetreeflag 
        tree = prunetree_afm(tree, branchlen, plot_value);
    end

	if plot
		hold off
    end
    

    if ignoreradiusflag
        radius_vec = ones(size(tree(:,6)));
        tree(:,6) = radius_vec;
    end
    % var9_1 means input ninth variable is 1
    curtime = clock;
    timelist = fix(curtime);
    timestring = [];
    for i = 1 : numel(timelist) 
        curstring = num2str(timelist(i));
        timestring = [timestring curstring];
    end
    outfilename = [prefix_outfilename timestring suffix_outfilename];
    rivuletpara.plot_value = plot_value;
    rivuletpara.percentage = percentage;
    rivuletpara.rewire = rewire;
    rivuletpara.gap = gap;
    rivuletpara.ax_value = ax_value;
    rivuletpara.dumpcheck = dumpcheck;
    rivuletpara.connectrate = connectrate;
    rivuletpara.branchlen = branchlen;
    rivuletpara.somagrowthcheck = somagrowthcheck;

    rivuletpara.cleanercheck = cleanercheck;
    rivuletpara.dtimageflag = dtimageflag;
    rivuletpara.atmapflag = atmapflag;
    rivuletpara.ignoreradiusflag = ignoreradiusflag;
    rivuletpara.prunetreeflag = prunetreeflag;
    rivuletpara.afmp = afmp;
    rivuletpara.speedastensorflag = speedastensorflag;
    rivuletpara.oofhmflag = oofhmflag;
    rivuletpara.boostveconeflag = boostveconeflag;
    rivuletpara.skeletonspeedflag = skeletonspeedflag;
    % showbibox(I);
    showswc(tree);
    % compareradiusoof;
    saveswc(tree, outfilename);
    savepara(rivuletpara, outfilename);
%     hold on
%     scatter3(branchlist(:,2), branchlist(:,1), branchlist(:,3), 'b');
%     hold off
end

**Comment by gr915** [comment] 2017-08-02 02:26
Thanks,but 147 line of your above code ,show error:Undefined function 'afm' for input arguments of type 'double'. i can't find any afm code in your file.

**Comment by donghaozhang** [comment] 2017-08-02 02:34
Yeah, this is not exactly same as trace.m. It was originally designed for another program. But the way to assign parameters is similar. You can transfer trace.m to comand-line by using all default parameters and comment gui stuff. Notice that I is the binary image.

**Comment by donghaozhang** [comment] 2017-08-02 02:49
@gr915 :) ! I just finished the command-line version which is exactly you asked for.

**Comment by donghaozhang** [comment] 2017-08-02 02:51
clear all; close all;
I = tifread('/home/donghao/Desktop/neurontracing/Gold166-JSON/FLY-JANELIA/1.tif');
threshold = 40;
I = I > threshold;

% The second input variable is plot
plot_value = false;
plot = false;

% The third input variable is percentage 
percentage = 0.98;

% The fourth input vairable is rewire
rewire =  false;

% The fifth input vairable is gap 
gap = 10;

% The sixth input variable is ax
ax_value = false;

% The seventh input variable is dumpcheck
dumpcheck = true;

% The eighth input variable is connectrate
connectrate = 1.2;

% The ninth input variable is branchlen
branchlen = 10;

% The tenth input variable is somagrowthcheck
somagrowthcheck = false;

% The eleventh input vairable is soma structure
% We only test the anisotropic fast marching at this point 
% so we do not include soma in this script 

% The twelfth input variable is cleanercheck
cleanercheck = false;

% The thirteenth input variable is dtimageflag
dtimageflag = false;


% The fourteenth input variable is tmapflag
atmapflag = true;

% The fifteenth input variable is ignoreradiusflag
ignoreradiusflag = true;

% The sixteenth input variable is prunetreeflag
prunetreeflag = false;


if plot
    axes(ax);
end
if (~dtimageflag)
    disp('Distance transform');
    notbI = not(I>0.5);
    bdist = bwdist(notbI, 'Quasi-Euclidean');
    bdist = bdist .* double(I);
    bdist = double(bdist);
    save('/home/donghao/Desktop/soma_case1.mat');
end

disp('Looking for the source point...')
if somagrowthcheck
    SourcePoint = [soma.x; soma.y; soma.z];
    somaidx = find(soma.I == 1);
    [somax, somay, somaz] = ind2sub(size(soma.I), somaidx);
    % Find the soma radius
    d = pdist2([somax, somay, somaz], [soma.x, soma.y, soma.z]);
    maxD = max(d);
else
    [SourcePoint, maxD] = maxDistancePoint(bdist, I, true);
end
disp('Make the speed image...');
SpeedImage=(bdist/maxD).^4;

clear bdist;
if somagrowthcheck
    fprintf('The soma field version 3 is running\n');
    somabI = soma.I > 0.5;
    % The following two lines find surface of the binary soma
    S=ones(3,3,3);
    Bsoma=xor(somabI,imdilate(somabI,S));
    dtsoma = bwdist(Bsoma);
    dtsoma = dtsoma + 1;
    dtsoma(dtsoma>15) = 1;
    fprintf('version 3 soma field is running\n');
    [Dx, Dy, Dz] = ind2sub(size(dtsoma),find(dtsoma > 1));
    minx = min(Dx);
    maxx = max(Dx);
    miny = min(Dy);
    maxy = max(Dy);
    minz = min(Dz);
    maxz = max(Dz);
    surf_dist = dtsoma(minx:maxx, miny:maxy, minz:maxz);
    clear dtsoma; clear S; clear Bsoma; clear somabI;
    % expotential_coefficient = 2 / estimated_radius;
    % The following is a test case which might not be necessary
    surf_scale = 1;
    surf_dist = (surf_dist * surf_scale);

    fprintf('Extract speed image box...\n');
    speed_box = SpeedImage(minx:maxx, miny:maxy, minz:maxz);
    fprintf('Surface distance enhancement convolution begins...\n');    
    speed_box = speed_box .* surf_dist;
    SpeedImage(minx:maxx, miny:maxy, minz:maxz) = speed_box;
end
% Third version soma field end

SpeedImage(SpeedImage==0) = 1e-10;
if plot
    axes(ax);
end 
disp('marching...');
T = msfm(SpeedImage, SourcePoint, false, false);
szT = size(T);
fprintf('the size of time map, x is : %d, y is : %d, z is : %d\n', szT(1), szT(2), szT(3));
disp('Finish marching')

if somagrowthcheck
    fprintf('Mark soma label on time-crossing map\n')
    T(soma.I==1) = -2;
end

if plot
    hold on 
end

tree = []; % swc tree
if somagrowthcheck
    fprintf('Initialization of swc tree.\n'); 
    tree(1, 1) = 1;
    tree(1, 2) = 1;
    tree(1, 3) = soma.x;
    tree(1, 4) = soma.y;
    tree(1, 5) = soma.z;
    % fprintf('source point x : %d, y : %d, z : %d.\n', uint8(SourcePoint(1)), uint8(SourcePoint(2)), uint8(SourcePoint(3)));         
    tree(1, 6) = 1;
    tree(1, 7) = -1;
end

prune = true;
% Calculate gradient of DistanceMap
disp('Calculating gradient...')
grad = distgradient(T);
if plot
    axes(ax);
end
S = {};
B = zeros(size(T));
if somagrowthcheck
    B = B | (soma.I>0.5);
end
lconfidence = [];
if plot
    [x,y,z] = sphere;
    plot3(x + SourcePoint(2), y + SourcePoint(1), z + SourcePoint(3), 'ro');
end

unconnectedBranches = {};
printcount = 0;
printn = 0;
while(true)

    StartPoint = maxDistancePoint(T, I, true);
    if plot
        plot3(x + StartPoint(2), y + StartPoint(1), z + StartPoint(3), 'ro');
    end

    if T(StartPoint(1), StartPoint(2), StartPoint(3)) == 0 || I(StartPoint(1), StartPoint(2), StartPoint(3)) == 0
        break;
    end

    [l, dump, merged, somamerged] = shortestpath2(T, grad, I, tree, StartPoint, SourcePoint, 1, 'rk4', gap);

    if (size(l, 1) == 0)
        l = StartPoint'; 
    end
    
    % Get radius of each point from distance transform
    radius = zeros(size(l, 1), 1);
    parfor r = 1 : size(l, 1)
        radius(r) = getradius(I, l(r, 1), l(r, 2), l(r, 3));
    end
    radius(radius < 1) = 1;
    assert(size(l, 1) == size(radius, 1));

    [covermask, centremask] = binarysphere3d(size(T), l, radius);
    % Remove the traced path from the timemap
    if cleanercheck & size(l, 1) > branchlen
        covermask = augmask(covermask, I, l, radius);
    end
    T(covermask) = -1;
    T(centremask) = -3;
    if ~((dump) && dumpcheck) 
        [tree, newtree, conf, unconnected] = addbranch2tree(tree, l, merged, connectrate, radius, I, branchlen, plot, somamerged);
        lconfidence = [lconfidence, conf];
    end

    B = B | covermask;

    percent = sum(B(:) & I(:)) / sum(I(:));
    if plot
        axes(ax);
    end
    printn = printn + 1;
    if percent >= percentage
        disp('Coverage reached end tracing...')
        break;
    end

end

meanconf = mean(lconfidence);

if cleanercheck
    disp('Fixing topology')
    tree = fixtopology(tree);
end 
tree = prunetree(tree, branchlen);

**Comment by gr915** [comment] 2017-08-02 08:58
Thank you for your answer in the morning, my input I is the 3d binary image.but the 204 line of above code ( B = B | covermask; percent = sum(B(:) & I(:)) / sum(I(:));) the sum(B(:) & I(:)) always is zero, the code dead loop in 209 line （if percent >= percentage）

**Comment by donghaozhang** [comment] 2017-08-02 09:04
If you already have the binary image, the first four lines you do not need.
clear all; close all;
I = tifread('/home/donghao/Desktop/neurontracing/Gold166-JSON/FLY-JANELIA/1.tif');
threshold = 40;
I = I > threshold;

**Comment by gr915** [comment] 2017-08-02 09:07
The first four lines I do not use, I use load('OP1 stack .mat');

**Comment by donghaozhang** [comment] 2017-08-02 09:14
@gr915 Can I have your email address? I can send my version code to you and test image.

**Comment by gr915** [comment] 2017-08-02 09:16
OK，823061087@qq.com, thank you !

**Comment by donghaozhang** [comment] 2017-08-02 09:25
@gr915 I just sent the email to you. the path of file is test/cmdr1.m.

**Comment by HNHPUwangchao** [comment] 2017-08-12 02:43
excuse me ! deal writer ,  I have got your version code from my sister,but in my computer,this code can not run well,what is your version of your matlab?

**Comment by donghaozhang** [comment] 2017-08-12 02:49
Matlab 2015 2016 should be the working version.

**Comment by HNHPUwangchao** [comment] 2017-08-12 03:01
thanks, i have two problem. i am a novice of Digital image processing professional 
 what is the  order of the run?
can i modify you code in my computer for running well?

**Comment by HNHPUwangchao** [comment] 2017-08-12 03:34
Excuse me ,deal writer, i have some problem in you code that the "startpoint"  has not changed.

**Comment by HNHPUwangchao** [comment] 2017-08-12 13:01
Thank you for your answer ,  the 204 line of above code ( B = B | covermask; percent = sum(B(:) & I(:)) / sum(I(:));) the sum(B(:) & I(:)) always is zero, the code dead loop in 209 line （if percent >= percentage）

**Comment by lsqshr** [comment] 2017-08-12 21:13
What kind of image are you trying to feed in? Could you send us a link to an example image?

**Comment by HNHPUwangchao** [comment] 2017-08-13 01:37
@lsqshr  I  have the example ,can you tell  me  you emill,i just send the example image.
can the code run well in your computer?

**Comment by lsqshr** [comment] 2017-08-13 19:26
Of course the code runs on our machines. It has been used by many researchers. @donghaozhang do you mind having a look at this? I don't have a matlab license here. 

@HNHPUwangchao you can host the image somewhere if the image is too large otherwise you can send it to me via email. lsqshr AT gmail DOT com

**Comment by lsqshr** [comment] 2017-08-13 19:28
@HNHPUwangchao again, you can also try the python version which contains a newer version of our algorithm.

**Comment by donghaozhang** [comment] 2017-08-14 01:58
@HNHPUwangchao Based on your information, it is difficult for me to figure out the bug location. I think we have to do the hard way. We can compare the workspace line by line and find out the problem. Later, I will send you a email of results of the first lines.

**Comment by lsqshr** [comment] 2017-08-14 02:30
@donghaozhang I think the problem might be the input image. We do not know what kind of image it is yet & what is being tried

**Comment by HNHPUwangchao** [comment] 2017-08-14 02:31
thanks dear
I am compara the workspace line by line,in this code,the loop can not get the result,because the "tree" is a empty forever. can you send me a source code which can run well in matlab rather than phython。




At 2017-08-14 09:58:02, "donghaozhang" <notifications@github.com> wrote:


@HNHPUwangchao Based on your information, it is difficult for me to figure out the bug location. I think we have to do the hard way. We can compare the workspace line by line and find out the problem. Later, I will send you a email of results of the first lines.

**Comment by HNHPUwangchao** [comment] 2017-08-14 02:42
I have read seriously your comment and use the 1.tif image，and the  first five lines of code are
 clear all;
 close all;
I = tifread('D:\王超资料\1.tif');
threshold = 40;
I = I > threshold;






At 2017-08-14 10:30:12, "Siqi Liu" <notifications@github.com> wrote:


@donghaozhang I think the problem might be the input image. We do not know what kind of image it is yet & what is being tried

**Comment by donghaozhang** [comment] 2017-08-14 02:45
@lsqshr They are testing the janelia 1.tif. The input image should be correct. I will confirm the result line by line via email.

**Comment by lsqshr** [comment] 2017-08-14 02:47
Great. Thanks for the help DH

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lsqshr** [comment] 2017-08-14 02:48
@HNHPUwangchao I think the problem is your threshold. For all big neuron first 2000 images, you need to set the threshold as 0, rather than 40.

**Comment by HNHPUwangchao** [comment] 2017-08-14 02:51
OK,thanks,I will change the threshold and run this code .
thanks again 





At 2017-08-14 10:48:56, "Siqi Liu" <notifications@github.com> wrote:


@HNHPUwangchao I think the problem is your threshold. For all big neuron first 2000 images, you need to set the threshold as 0, rather than 40.

**Comment by HNHPUwangchao** [comment] 2017-08-14 03:03
so terrible , in workspace the "standpoint "also never change ,and the result is a empty array.




At 2017-08-14 10:48:56, "Siqi Liu" <notifications@github.com> wrote:


@HNHPUwangchao I think the problem is your threshold. For all big neuron first 2000 images, you need to set the threshold as 0, rather than 40.

**Closed as completed** 2017-08-14 03:04 UTC

**Comment by lsqshr** [comment] 2017-08-14 03:05
@HNHPUwangchao have you tried any other image from the first 2000 dataset with threshold of 0?

**Comment by lsqshr** [comment] 2017-08-14 03:06
It's weird because we were using the first 2000-1 image for lots of testing

**Comment by HNHPUwangchao** [comment] 2017-08-14 03:25
I think my problem have not solve.  o my god! 





At 2017-08-14 11:06:29, "Siqi Liu" <notifications@github.com> wrote:


It's weird because we were using the first 2000-1 image for lots of testing

**Comment by HNHPUwangchao** [comment] 2017-08-14 03:31
dear ,do you consider this loop of the code have problem? 





在 2017-08-14 11:03:29，"测控王超" <13137916153@163.com> 写道：



so terrible , in workspace the "standpoint "also never change ,and the result is a empty array.




At 2017-08-14 10:48:56, "Siqi Liu" <notifications@github.com> wrote:


@HNHPUwangchao I think the problem is your threshold. For all big neuron first 2000 images, you need to set the threshold as 0, rather than 40.

**Comment by lsqshr** [comment] 2017-08-14 03:44
No. There should not be bug in the algorithm code. This code has been used to generate thousands of neuron models. 

I need you to double check a few things. 
1. Have you run the mexall.m to build the c code? Any errors?
2. On which OS and matlab version you are trying to run this code?
3. Have you tried any other image rather than the 2000-1? Do you see the same issue?

**Comment by lsqshr** [comment] 2017-08-14 03:47
Also, have you tried to rescale the image? Or are you using the original resolution?

**Comment by HNHPUwangchao** [comment] 2017-08-14 06:02
dear，
thanks for your guide sincerely，i will adjast this code base on your advices.









在 2017-08-14 11:47:08，"Siqi Liu" <notifications@github.com> 写道：


Also, have you tried to rescale the image? Or are you using the original resolution?
